version: '3.8'

services:
  c-ticket:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: c-ticket-app
    ports:
      - "3000:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
